spring:
  datasource:
    url: jdbc:postgresql://trip-db:5432/trip_db
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}

server:
  port: ${SERVER_PORT:8085}

ridex:
  services:
    pricing:
      base-url: ${PRICING_SERVICE_URL:http://pricing-service:8087}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://eureka-server:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true

  instance:
    prefer-ip-address: true

logging:
  level:
    com.netflix.discovery: WARN
    com.netflix.eureka: WARN
    org.springframework.cloud.netflix.eureka: WARN
    org.springframework.cloud.loadbalancer: WARN